// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// OrderedNumbersFetcher is an autogenerated mock type for the OrderedNumbersFetcher type
type OrderedNumbersFetcher struct {
	mock.Mock
}

type OrderedNumbersFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderedNumbersFetcher) EXPECT() *OrderedNumbersFetcher_Expecter {
	return &OrderedNumbersFetcher_Expecter{mock: &_m.Mock}
}

// FetchOrderedNumbers provides a mock function with given fields: ctx
func (_m *OrderedNumbersFetcher) FetchOrderedNumbers(ctx context.Context) ([]int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchOrderedNumbers")
	}

	var r0 []int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderedNumbersFetcher_FetchOrderedNumbers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchOrderedNumbers'
type OrderedNumbersFetcher_FetchOrderedNumbers_Call struct {
	*mock.Call
}

// FetchOrderedNumbers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *OrderedNumbersFetcher_Expecter) FetchOrderedNumbers(ctx interface{}) *OrderedNumbersFetcher_FetchOrderedNumbers_Call {
	return &OrderedNumbersFetcher_FetchOrderedNumbers_Call{Call: _e.mock.On("FetchOrderedNumbers", ctx)}
}

func (_c *OrderedNumbersFetcher_FetchOrderedNumbers_Call) Run(run func(ctx context.Context)) *OrderedNumbersFetcher_FetchOrderedNumbers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *OrderedNumbersFetcher_FetchOrderedNumbers_Call) Return(_a0 []int, _a1 error) *OrderedNumbersFetcher_FetchOrderedNumbers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderedNumbersFetcher_FetchOrderedNumbers_Call) RunAndReturn(run func(context.Context) ([]int, error)) *OrderedNumbersFetcher_FetchOrderedNumbers_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderedNumbersFetcher creates a new instance of OrderedNumbersFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderedNumbersFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderedNumbersFetcher {
	mock := &OrderedNumbersFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
