// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RawNumbersFetcher is an autogenerated mock type for the RawNumbersFetcher type
type RawNumbersFetcher struct {
	mock.Mock
}

type RawNumbersFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *RawNumbersFetcher) EXPECT() *RawNumbersFetcher_Expecter {
	return &RawNumbersFetcher_Expecter{mock: &_m.Mock}
}

// FetchRawNumbers provides a mock function with given fields: ctx
func (_m *RawNumbersFetcher) FetchRawNumbers(ctx context.Context) ([]any, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchRawNumbers")
	}

	var r0 []any
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]any, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []any); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]any)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RawNumbersFetcher_FetchRawNumbers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchRawNumbers'
type RawNumbersFetcher_FetchRawNumbers_Call struct {
	*mock.Call
}

// FetchRawNumbers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RawNumbersFetcher_Expecter) FetchRawNumbers(ctx interface{}) *RawNumbersFetcher_FetchRawNumbers_Call {
	return &RawNumbersFetcher_FetchRawNumbers_Call{Call: _e.mock.On("FetchRawNumbers", ctx)}
}

func (_c *RawNumbersFetcher_FetchRawNumbers_Call) Run(run func(ctx context.Context)) *RawNumbersFetcher_FetchRawNumbers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RawNumbersFetcher_FetchRawNumbers_Call) Return(_a0 []any, _a1 error) *RawNumbersFetcher_FetchRawNumbers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RawNumbersFetcher_FetchRawNumbers_Call) RunAndReturn(run func(context.Context) ([]any, error)) *RawNumbersFetcher_FetchRawNumbers_Call {
	_c.Call.Return(run)
	return _c
}

// NewRawNumbersFetcher creates a new instance of RawNumbersFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRawNumbersFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *RawNumbersFetcher {
	mock := &RawNumbersFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
